In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np  
import utils as U

from pathlib import Path

OUTPUT = Path('output')

sns.set_theme(style="whitegrid")

## Utils here

In [ ]:
def save_fig(name, fig_extension='pdf'):
    path = OUTPUT / f'{name}.{fig_extension}'
    plt.savefig(path, format=fig_extension)


def explicit_mean(series):
    n = len(series)

    total = 0
    for x in series:
        total += x
    return total / n


def explicit_variance(series):
    n = len(series)
    m = explicit_mean(series)

    sq_diff = 0
    for x in series:
        sq_diff += (x - m) ** 2
    return sq_diff / (n - 1)

# Load & Pre-processing

In [ ]:
df = pd.read_csv('heart+disease\processed.cleveland.data', header=None,
                 na_values='?')
df.columns = [
    'age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 
    'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'
]

target_columns = ['age', 'sex', 'thalach', 'target']
df = df[target_columns]

df['target'] = (df['target'] > 0).astype(int)

<>:12: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
<>:12: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
C:\Users\kevin\AppData\Local\Temp\ipykernel_3592\1480445759.py:12: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
  df = pd.read_csv('heart+disease\processed.cleveland.data', header=None,

In [26]:
df.head()

    age  sex  thalach  target
0  63.0  1.0    150.0       0
1  67.0  1.0    108.0       1
2  67.0  1.0    129.0       1
3  37.0  1.0    187.0       0
4  41.0  0.0    172.0       0

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   age      303 non-null    float64
 1   sex      303 non-null    float64
 2   thalach  303 non-null    float64
 3   target   303 non-null    int64
dtypes: float64(3), int64(1)
memory usage: 9.6 KB

In [28]:
print(df.isnull().sum())

age        0
sex        0
thalach    0
target     0
dtype: int64

In [29]:
df.describe().T

         count        mean        std   min    25%    50%    75%    max
age      303.0   54.438944   9.038662  29.0   48.0   56.0   61.0   77.0
sex      303.0    0.679868   0.467299   0.0    0.0    1.0    1.0    1.0
thalach  303.0  149.607261  22.875003  71.0  133.5  153.0  166.0  202.0
target   303.0    0.458746   0.499120   0.0    0.0    0.0    1.0    1.0

# Part One

## Age frequency distribution

In [30]:
max_v = df['age'].max()
min_v = df['age'].min()

amplitude = max_v - min_v

k = 1 + 3.332 * np.log10(56)
k = round(k)

h = amplitude / k
h = round(h)

print(f'amplitude: {amplitude}')
print(f'k:         {k}')
print(f'h:         {h}')

amplitude: 48.0
k:         7
h:         7

In [31]:
intervals = []
start = min_v

for i in range(k):
    end = start + h
    intervals.append((start, end))
    start = end

interval_bastions = []
for i in intervals:
    interval_bastions.append(i[0])
interval_bastions.append(intervals[-1][1])

In [32]:
data = pd.Series(df['age'])

idx = pd.interval_range(start=min_v, end=interval_bastions[-1], periods=k, closed='left')
frequencies_table = pd.DataFrame(index=idx)
df.index

RangeIndex(start=0, stop=303, step=1)

In [33]:
counts = pd.cut(data, bins=interval_bastions, right=False).value_counts().sort_index()
frequencies_table['fi'] = counts.values
frequencies_table['fr'] = frequencies_table['fi'] / df['age'].shape[0]
frequencies_table['fraci'] = frequencies_table['fr'].cumsum()
frequencies_table['pmi'] = [interval.mid for interval in frequencies_table.index]

In [34]:
frequencies_table

              fi        fr     fraci   pmi
[29.0, 36.0)   7  0.023102  0.023102  32.5
[36.0, 43.0)  29  0.095710  0.118812  39.5
[43.0, 50.0)  51  0.168317  0.287129  46.5
[50.0, 57.0)  75  0.247525  0.534653  53.5
[57.0, 64.0)  90  0.297030  0.831683  60.5
[64.0, 71.0)  45  0.148515  0.980198  67.5
[71.0, 78.0)   6  0.019802  1.000000  74.5

In [38]:
mean = U.explicit_mean(df['age'])
var = U.explicit_variance(df['age'])
std = np.sqrt(var)

print(f'mean: {mean:.4f}'
      f'\nvar:  {var:.4f}'
      f'\nstd:  {std:.4f}')

mean: 54.4389
var:  81.6974
std:  9.0387

# Part Two

# Part Three

# Part Four

# Part Five